import Dashboard from '@/Components/My Dashboard/Dashboard'
import React from 'react'

export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Dashboard/>
    </>
  )
}
