import Faq from '@/Components/ FrequentlyQuestion/Faq'
import React from 'react'

export const metadata = {
    title: "Frequently Ask Question",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <Faq />
        </>
    )
}
