
import Checkout from "@/Components/Checkout";

export const metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default function Main() {
  return (
    <>
      <Checkout/>
    </>
  );
}