import FrameSection from '@/Components/Common/FrameSection';
import React from 'react'
import MainLayout from '../../layout';
export const metadata = {
    title: "Product listing",
    description: "Generated by create next app",
  };
  
export default function page() {
  return (
    <>
      <FrameSection title = {"Product Listing"}/>
    </>
  )
}
