import ContactUs from "../../Components/ContactUs";

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function Main() {
  return (
    <>
       <ContactUs/>
    </>
  );
}