
import AboutUs from "@/Components/AboutUs/AboutUs";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function Main() {
  return (
    <>
        <AboutUs/>
    </>
  );
}