import WishList from '@/Components/WishList/WishList'
import React from 'react'

export const metadata = {
  title: "Wishlist",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
       <WishList/>
    </>
  )
}
