import ProductDetails from '@/Components/ProductDetails/ProductDetails'
import React from 'react'

export const metadata = {
  title: "Product Details",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
     <ProductDetails/>
    </>
  )
}
