import ShopingCart from '@/Components/Cart/ShopingCart'
import React from 'react'

export const metadata = {
    title: "Cart",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <ShopingCart />
        </>
    )
}
