import Term from '@/Components/TermOfUse/Term'
import React from 'react'
import MainLayout from '../layout';

export const metadata = {
    title: "Term of Use",
    description: "Generated by create next app",
};
export default function page() {
    return (
        <>
            <Term />
        </>
    )
}
