import './Css/Style.css';
import MyApps from '@/Components/MyApps';
import Header from '@/Components/Common/Header';
import Footer from '@/Components/Common/Footer';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: "Online furniture in Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <MyApps> 
          <Header />
          <ToastContainer/>
          {children}
          <Footer />
        </MyApps>
      </body>
    </html>
  );
}
