import Privacy from '@/Components/PrivacyPolicy/Privacy';
import React from 'react'
export const metadata = {
    title: "Privacy policy",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <>
        <Privacy/>
    </>
  )
}
